from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    admin_home,
    customer_login,
    customer_register,
    customer_home,
    profile_settings,
    logout_view,
    view_menu,
    add_to_cart,
    add_to_cart_from_search,
    view_cart,
    remove_cart_item,
    toggle_favorite,
    search_results,
    update_cart_item_quantity,
    get_cart_count,
    view_favorites,
    admin_base,
    owner_view_restaurant,
    owner_add_restaurant,
    delete_restaurant,
    rider_register,
    owner_edit_restaurant,
    owner_add_menu,
    owner_view_menu,
    owner_edit_menu,
    owner_delete_menu,
    admin_rider_table,
    manage_rider_application,
    add_favorite_to_cart,
    otp_verification,
    foodhitch,
    check_out,
    rider_base,
    rider_home,
    admin_feedback_list,
    approve_feedback,
    reject_feedback,
    update_rider_profile,
    customer_track_order,
    submit_feedback,
    order_history,
    partner,
    customer_reward_points,
    owners_register,
    owner_base,
    partner_request_list,
    manage_business_request,
    admin_notifications,
    restaurant_partners,
    rider_delivery_history,
    rider_transactions,
    rider_profile_update,
    calculate_delivery_fee,
    place_order, 
    get_rider_location,
    view_riders,
    delete_rider,
    update_delivery_status,
    rider_earnings,
    rider_notifications,
    update_store_owner_profile, reorder, update_availability, password_reset_request, password_reset_set,
    check_username, remove_favorite, order_completed, verify_otp, owner_restaurants, archive_delivery, rider_archived_deliveries,
    chat_room
)

urlpatterns = [
    # Authentication
    path('', foodhitch, name='foodhitch'),
    path('customer_register/', customer_register, name='customer_register'),
    path('customer_login/', customer_login, name='customer_login'),
    path('rider_register/', rider_register, name='rider_register'),
    path('profile_settings/', profile_settings, name='profile_settings'),
    path('rider_base/', rider_base, name='rider_base'),
    path('rider_home/', rider_home, name='rider_home'),
    path('logout/', logout_view, name='logout'),
    path('verify_otp/', verify_otp, name='verify_otp'),
    path('owner/<int:owner_id>/restaurants/', owner_restaurants, name='owner_restaurants'),
    path('archive-delivery/<int:delivery_id>/', archive_delivery, name='archive_delivery'),
    path('archived-deliveries/', rider_archived_deliveries, name='rider_archived_deliveries'),
    


    # Customer and Menu 
    path('otp-verification/', otp_verification, name='otp_verification'),
    path('customer_home/', customer_home, name='customer_home'),
    path('restaurant/<int:restaurant_id>/customer_menu/', view_menu, name='view_menu'),
    path('add_to_cart/', add_to_cart, name='add_to_cart'),
    path('add_to_cart_from_search/', add_to_cart_from_search, name='add_to_cart_from_search'),
    path('view_cart/', view_cart, name='view_cart'),
    path('search/', search_results, name='search_results'),
    path('remove_cart_item/<int:item_id>/', remove_cart_item, name='remove_cart_item'),
    path('toggle_favorite/', toggle_favorite, name='toggle_favorite'),
    path('update_cart_item_quantity/<int:item_id>/', update_cart_item_quantity, name='update_cart_item_quantity'),
    path('get_cart_count/', get_cart_count, name='get_cart_count'),
    path('add_favorite_to_cart/<int:food_id>/', add_favorite_to_cart, name='add_favorite_to_cart'),
    path('view_favorites/', view_favorites, name='view_favorites'),
    path('profile/update/', update_rider_profile, name='update_rider_profile'),
    path('track_order/', customer_track_order, name='customer_track_order'),
    path('order-history/', order_history, name='order_history'),
    path('reward_points/', customer_reward_points, name='customer_reward_points'),
    path('rider/earnings/', rider_earnings, name='rider_earnings'),
    path('reorder/<int:order_id>/', reorder, name='reorder'),
     path('update_availability/', update_availability, name='update_availability'),
     path('remove_favorite/<int:food_id>/', remove_favorite, name='remove_favorite'),

    # Admin
    path('admin_home/', admin_home, name='admin_home'),
    path('admin_base/', admin_base, name='admin_base'),


    # Owner Routes
    path('owner_view_restaurant/', owner_view_restaurant, name='owner_view_restaurant'),
    path('owner_add_restaurant/', owner_add_restaurant, name='owner_add_restaurant'),
    path('delete-restaurant/<int:restaurant_id>/', delete_restaurant, name='delete_restaurant'),
    path('restaurant/<int:restaurant_id>/edit/', owner_edit_restaurant, name='owner_edit_restaurant'),
    path('restaurant/<int:restaurant_id>/owner_add_menu/', owner_add_menu, name='owner_add_menu'),
    path('restaurant/<int:restaurant_id>/owner_menu/', owner_view_menu, name='owner_view_menu'),
    path('restaurant/<int:restaurant_id>/menu/<int:food_id>/edit/', owner_edit_menu, name='owner_edit_menu'),
    path('delete-menu/<int:restaurant_id>/<int:food_id>/', owner_delete_menu, name='owner_delete_menu'),

    # Other Routes
    path('riders/', admin_rider_table, name='admin_rider_table'),
    path('riders/<int:RiderID>/', manage_rider_application, name='manage_rider_application'),
    path('feedback/', admin_feedback_list, name='admin_feedback_list'),
    path('feedback/approve/<int:feedback_id>/', approve_feedback, name='approve_feedback'),
    path('feedback/reject/<int:feedback_id>/', reject_feedback, name='reject_feedback'),
    path('submit_feedback/<int:delivery_id>/', submit_feedback, name='submit_feedback'),
    path('notifications/', admin_notifications, name='admin_notifications'),
    path('rider_notifications/', rider_notifications, name='rider_notifications'),
    path('restaurant-partners/', restaurant_partners, name='restaurant_partners'),

    # Check Out
    path('partner/', partner, name='partner'),
    path('check_out/', check_out, name='check_out'),
    path('calculate-delivery-fee/', calculate_delivery_fee, name='calculate_delivery_fee'),
    path('owners_register/', owners_register, name='owners_register'),
    path('owner_base/', owner_base, name='owner_base'),
    path('partner-requests/', partner_request_list, name='partner_request_list'),
    path('manage_business_request/<int:restaurant_id>/', manage_business_request, name='manage_business_request'),
    path('rider_delivery_history/', rider_delivery_history, name='rider_delivery_history'),
    path('rider_transactions/', rider_transactions, name='rider_transactions'),
    path('rider_profile_update/', rider_profile_update, name='rider_profile_update'),
    path('place_order/', place_order, name='place_order'),
    path('rider/location/<int:RiderID>/', get_rider_location, name='get_rider_location'),
    path('view_riders/', view_riders, name='view_riders'),
    path('view_riders/<int:rider_id>/delete/', delete_rider, name='delete_rider'),
    path('update-delivery-status/', update_delivery_status, name='update_delivery_status'),
    path('store-owner/update/', update_store_owner_profile, name='update_store_owner_profile'),
    path('password-reset/', password_reset_request, name='password_reset_request'),
    path('password-reset/set/', password_reset_set, name='password_reset_set'),
    path('check_username/', check_username, name='check_username'),  # Add this line
    path('order-completed/', order_completed, name='order_completed'),

    path('chat/<int:delivery_id>/', chat_room, name='customer_chat_room'),  # For customers
    path('rider/chat/<int:delivery_id>/', chat_room, name='chat_room'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
