# Generated by Django 5.1.1 on 2024-09-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=11)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='customer_pictures')),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
    ]
