# Generated by Django 5.1.1 on 2024-09-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0003_remove_customer_email_remove_customer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='Password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='Username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
    ]
