# Generated by Django 5.1.1 on 2024-09-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0004_customer_email_customer_password_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RestaurantName', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='restaurant_images')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('FoodID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.restaurant')),
            ],
        ),
    ]
