# Generated by Django 5.1.1 on 2024-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0005_restaurant_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images'),
        ),
    ]
