# Generated by Django 5.0.7 on 2024-09-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0007_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('FavoriteID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=255)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.customer')),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.menu')),
            ],
        ),
    ]
