# Generated by Django 5.0.7 on 2024-09-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0008_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
