# Generated by Django 5.0.7 on 2024-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0010_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='License',
            field=models.ImageField(blank=True, null=True, upload_to='rider_pictures'),
        ),
    ]
