# Generated by Django 5.0.7 on 2024-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0014_rider_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('bir_203_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
