# Generated by Django 5.0.7 on 2024-09-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0015_partnerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersFeedback',
            fields=[
                ('FeedbackID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
                ('Message', models.TextField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.customer')),
                ('RiderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.rider')),
            ],
            options={
                'verbose_name_plural': 'Customers Feedback',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('DeliveryID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Address', models.CharField(max_length=255)),
                ('OrderTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DeliveryFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalPayableAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DeliveryStatus', models.CharField(default='Pending', max_length=50)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.customer')),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.menu')),
                ('RiderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.BigAutoField(primary_key=True, serialize=False)),
                ('OrderTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.customer')),
                ('DeliveryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.delivery')),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.menu')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.order'),
        ),
    ]
