# Generated by Django 5.0.7 on 2024-09-16 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0016_customersfeedback_delivery_order_delivery_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersfeedback',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customersfeedback',
            name='Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
