# Generated by Django 5.0.7 on 2024-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0017_customersfeedback_date_customersfeedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='RiderLatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='RiderLongitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
