# Generated by Django 5.0.7 on 2024-09-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0018_delivery_riderlatitude_delivery_riderlongitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='DeliveryID',
        ),
    ]
