# Generated by Django 5.0.7 on 2024-09-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0019_remove_order_deliveryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='DeliveryStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Transit', 'On Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
