# Generated by Django 5.0.7 on 2024-09-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0022_customer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='TransactionID',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
