# Generated by Django 5.0.7 on 2024-09-21 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0023_order_transactionid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerRequest',
        ),
    ]
