# Generated by Django 5.0.7 on 2024-09-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0025_storeowner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeowner',
            options={'verbose_name_plural': 'Store Owner'},
        ),
        migrations.AddField(
            model_name='storeowner',
            name='HasBIR203',
            field=models.BooleanField(default=False, verbose_name='Do you have a BIR 203?'),
        ),
    ]
