# Generated by Django 5.0.7 on 2024-09-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0027_alter_storeowner_options_menu_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Status',
        ),
    ]
