# Generated by Django 5.0.7 on 2024-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0029_storeowner_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rider',
            options={},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='RiderLatitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='RiderLongitude',
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
