# Generated by Django 5.0.7 on 2024-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0030_alter_customer_options_alter_rider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='BusinessPermit',
            field=models.ImageField(blank=True, null=True, upload_to='businesspermit_images'),
        ),
    ]
