# Generated by Django 5.0.7 on 2024-09-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0033_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='Longitude',
        ),
    ]
