# Generated by Django 5.0.7 on 2024-09-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0035_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='Availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=12),
        ),
        migrations.AddField(
            model_name='rider',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
