# Generated by Django 5.0.7 on 2024-10-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0036_rider_availability_rider_latitude_rider_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Password',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
