# Generated by Django 5.0.7 on 2024-10-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0040_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersfeedback',
            name='DeliveryID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DeliveryStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Transit', 'On Transit'), ('Delivered', 'Delivered'), ('Received', 'Received')], default='Pending', max_length=50),
        ),
    ]
