# Generated by Django 5.0.7 on 2024-10-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0041_customersfeedback_deliveryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersfeedback',
            name='DeliveryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.delivery'),
        ),
    ]
