# Generated by Django 5.0.7 on 2024-10-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0042_alter_customersfeedback_deliveryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='FoodID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='FoodID',
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='FoodHitchApp.delivery')),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.menu')),
            ],
        ),
    ]
