# Generated by Django 5.0.7 on 2024-10-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0044_delivery_cartitems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='CartItems',
        ),
    ]
