# Generated by Django 5.0.7 on 2024-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0045_remove_delivery_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
