# Generated by Django 5.0.7 on 2024-10-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0046_alter_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
